---
- name: Ensure Delta Web compile directory exists
  ansible.builtin.file:
    path: "{{ delta_web_compile_dir }}"
    state: directory
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0755'

- name: Check out Delta Web
  ansible.builtin.git:
    repo: https://github.com/application-research/delta-nextjs-client.git
    dest: "{{ delta_web_compile_dir }}"
    version: "{{ delta_web_version }}"
    force: true
    update: true
  become_user: "{{ delta_system_user | default('delta') }}"
  register: delta_web_checkout

- name: If Delta git repository changed, clean up old builds
  ansible.builtin.command:
    chdir: "{{ delta_web_compile_dir }}"
    cmd: "rm -r .next"
  become_user: "{{ delta_system_user | default('delta') }}"
  when: delta_web_checkout.changed

- name: Build Delta Web # noqa 301
  ansible.builtin.shell:
    chdir: "{{ delta_web_compile_dir }}"
    cmd: "export NEXT_PUBLIC_API_URL='{{ delta_dm_api_url }}' ; npm install && npm run build"
    creates: "{{ delta_web_compile_dir }}/.next"
  become_user: "{{ delta_system_user | default('delta') }}"
  notify: Restart Delta Web

- name: Install Delta Web systemd service from template
  ansible.builtin.template:
    src: delta-web.service.j2
    dest: /etc/systemd/system/delta-web.service
    owner: root
    group: root
    mode: '0644'

- name: Start and enable Delta Web service
  ansible.builtin.service:
    name: delta-web
    state: started
    enabled: true
    daemon_reload: true
  notify: Restart Delta Web