---
- name: Compile and deploy Delta
  hosts: delta_node
  become: true

  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - role: zorlin.rust
      become_user: "{{ delta_system_user | default('delta') }}"
    - role: arg-delta