---
- name: Compile and deploy Delta
  hosts: delta_node
  become: true

  vars_files:
    - "vars/settings.yml"

  # We setup the Delta user outside of the role because otherwise things like Rust and Go installation may fail.
  pre_tasks:
    - name: Install the acl package
      ansible.builtin.package:
        name: acl
        state: present

    - name: Create a group for Delta
      ansible.builtin.group:
        name: "{{ delta_system_group | default('delta') }}"
        system: true

    - name: Create a user for Delta
      ansible.builtin.user:
        name: "{{ delta_system_user | default('delta') }}"
        group: "{{ delta_system_group | default('delta') }}"
        home: "{{ delta_system_home | default('/var/lib/arg-delta') }}"
        shell: /bin/bash
        createhome: true
        system: true

  roles:
    - role: gantsign.golang
      golang_gopath: '$HOME/workspace-go'
    - role: zorlin.rust
    - role: arg-delta
