---
- name: Install a build toolchain and dependencies
  ansible.builtin.package:
    name:
      - git
      - make
      - build-essential
      - wget
      - jq
      - hwloc
      - ocl-icd-opencl-dev
      - libhwloc-dev
      - pkg-config
    state: present

- name: Install packages needed for Ansible
  ansible.builtin.package:
    name:
      - acl
    state: present

- name: Ensure compile directory exists
  ansible.builtin.file:
    path: "{{ compile_dir }}"
    state: directory
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0755'

- name: Ensure Delta data directory exists
  ansible.builtin.file:
    path: "{{ delta_main_dir }}"
    state: directory
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0755'

- name: Ensure Delta blockstore directory exists
  ansible.builtin.file:
    path: "{{ delta_blockstore_dir }}"
    state: directory
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0755'

- name: Ensure Delta main directory exists
  ansible.builtin.file:
    path: "{{ delta_main_dir }}/delta"
    state: directory
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0755'

- name: Check out Delta
  ansible.builtin.git:
    repo: https://github.com/application-research/delta.git
    dest: "{{ compile_dir }}"
    version: "{{ delta_version }}"
    force: true
    update: true
  become_user: "{{ delta_system_user | default('delta') }}"

- name: Build Delta  # noqa 301
  ansible.builtin.shell:
    chdir: "{{ compile_dir }}"
    cmd: ". /etc/profile.d/golang.sh && make all"
    creates: "{{ compile_dir }}/delta"
  become_user: "{{ delta_system_user | default('delta') }}"
  notify: Restart Delta

- name: Install Delta
  ansible.builtin.copy:
    src: "{{ compile_dir }}/delta"
    dest: "{{ binary_install_dir }}/delta"
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0755'
    remote_src: true

- name: Install Delta systemd service from template
  ansible.builtin.template:
    src: delta.service.j2
    dest: /etc/systemd/system/delta.service
    owner: root
    group: root
    mode: '0644'

- name: Configure Delta
  ansible.builtin.template:
    src: delta.cfg.j2
    dest: /etc/default/delta
    owner: root
    group: root
    mode: '0644'
  notify: Reload Delta

- name: Install .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ delta_main_dir}}/delta/.env"
    owner: "{{ delta_system_user | default('delta') }}"
    group: "{{ delta_system_group | default('delta') }}"
    mode: '0644'

- name: Enable and start Delta systemd service
  ansible.builtin.systemd:
    name: delta
    state: started
    enabled: true
    daemon_reload: true
